# permissions for end users to view helmuninstallers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmuninstaller-viewer-role
rules:
- apiGroups:
  - mikutas.example.com
  resources:
  - helmuninstallers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mikutas.example.com
  resources:
  - helmuninstallers/status
  verbs:
  - get
